name: LibTorch Linux CUDA x86_64

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The name of the branch you want to build.
        required: true

jobs:
  build:
    runs-on: ['self-hosted', 'linux', 'x64']
    strategy:
      matrix:
        cuda: ['118', '124']
        config: ['Debug', 'Release']
        include:
          - cuda: '118'
            container: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

          - cuda: '124'
            container: nvidia/cuda:12.4.1-cudnn-devel-ubuntu20.04

    container: ${{ matrix.container }}
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v3
      - name: Install compilation tools
        run: |
          apt-get update
          apt-get install -y build-essential
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pytorch
      - name: Conda deps
        run: |
          conda install cmake ninja python git zip
      - name: Install MAGMA
        run: |
          conda install -c pytorch magma-cuda${{ matrix.cuda }}
      - name: Clone
        run: |
          git clone -b ${{ github.event.inputs.branch }} --recurse-submodule https://github.com/pytorch/pytorch.git
      - name: Install deps
        run: | 
          cd pytorch
          pip install -r requirements.txt
          pip install mkl-static mkl-include
      - name: Build Libtorch
        run: |
          mkdir pytorch-build
          cd pytorch-build
          cmake \
            -DBUILD_SHARED_LIBS:ON \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DBUILD_PYTHON=OFF \
            -DUSE_CUDA=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=../libtorch \
            ../pytorch
          cmake --build . --target install --parallel 8 --config ${{ matrix.config }}
      - name: Create archive
        run: |
          zip -r libtorch-linux-cuda${{ matrix.cuda }}-${{ matrix.config }}-x86_64-${{ github.event.inputs.branch }}.zip libtorch/
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libtorch-linux-cuda${{ matrix.cuda }}-${{ matrix.config }}-x86_64-${{ github.event.inputs.branch }}.zip
          overwrite: true
          file_glob: true
          tag: LibTorch-for-R

