name: LibTorch Linux x86_64

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The name of the branch you want to build.
        required: true

jobs:
  build:
    runs-on: ['ubuntu-latest']
    container: ubuntu:20.04
    strategy:
      matrix:
        shared: [ON, OFF]
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - name: Install compilation tools
        run: |
          apt-get update
          apt-get install -y build-essential
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pytorch
      - name: Conda deps
        run: |
          conda install cmake ninja python git zip
      - name: Clone
        run: |
          git clone -b ${{ github.event.inputs.branch }} --recurse-submodule https://github.com/pytorch/pytorch.git
      - name: Install deps
        run: | 
          cd pytorch
          pip install -r requirements.txt
          pip install mkl-static mkl-include
      - name: Build Libtorch
        run: |
          mkdir pytorch-build
          cd pytorch-build
          cmake \
            -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DBUILD_PYTHON=OFF \
            -DUSE_CUDA=OFF \
            -DCMAKE_INSTALL_PREFIX:PATH=../libtorch \
            ../pytorch
          cmake --build . --target install --parallel 4
      - name: Create archive
        run: |
          zip -r libtorch-linux-x86_64-${{ matrix.shared == 'ON' && 'shared' || 'static' }}-${{ github.event.inputs.branch }}.zip libtorch/
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libtorch-linux-x86_64-${{ matrix.shared == 'ON' && 'shared' || 'static' }}-${{ github.event.inputs.branch }}.zip
          overwrite: true
          file_glob: true
          tag: LibTorch-for-R

